name: Pipeline

on: push

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Setup pip and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry

            - name: Setup poetry
              run: |
                poetry install

            - name: Run black
              run: |
                poetry run black ./**/*.py --check

            
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Setup pip and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry

            - name: Setup poetry
              run: |
                poetry install

            - name: Run tests
              run: |
                poetry run coverage run pytest tests/

            - name: Create coverage json
              run: |
                if [ -f ".coverage" ] then coverage json; fi

            - name: Update Coverage Badge
              # GitHub actions: default branch variable
              # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
              if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              uses: we-cli/coverage-badge-action@main
            
