name: Pipeline

on: push

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Setup pip and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                pip install invoke

            - name: Setup poetry
              run: |
                invoke init

            - name: Run black
              run: |
                invoke lint

            
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Setup pip and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry
                pip install invoke

            - name: Setup poetry
              run: |
                invoke init

            - name: Run tests
              run: |
                invoke test

            - name: Update Coverage Badge
              # GitHub actions: default branch variable
              # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
              if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              uses: we-cli/coverage-badge-action@main
            
